server:
  port: 9998
  servlet:
    context-path: /

# logback 配置
logging:
  file:
    path: classpath:/logback-spring.xml
  level:
    root: debug
    boot: info
  path: ./logs

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Wed114130
    url: jdbc:mysql://yiidii.cn:3306/panel?useUnicode=true&characterEncoding=UTF-8
    username: root

mybatis:
  mapperLocations: classpath*:mapper/**/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    count: countSql
  page-size-zero: true




